### ISSUE TITLE
Switch web server away from Thin

### ISSUE THREAD

**Issue by hummusonrails** [nexmo-community/nexmo-ruby-websockets#1]
This project is built using the `thin` web server, which has not been actively updated for a while. It still works and is sufficient, but would be a good thing to switch to a more actively maintained web server, perhaps [Puma](https://github.com/puma/puma). 

The web server dependency needs to be updated, and the respective code inside the application would need to be refactored for the new server as well.

Bonus: Add tests to validate the success of the change! 🌟

**Comment by gnomex** [comment]
Hi Ben, have you considered to move your solution to sinatra?

it will be easier to setup and use raw websockets with puma + sinatra + faye-websocket.

**Comment by hummusonrails** [comment]
Hey @gnomex, I've considered it. The original intent was to build a demo with the most basic tooling and limit reliance on more complex frameworks. However, I'd be interested to see a Sinatra solution if you want to raise it as a PR!

**Comment by distributedlock** [comment]
Hello @bencgreenberg, I have opened a PR for the Puma solution migrating away from Thin. Please let me know if you prefer any changes. Cheers!

**Comment by hummusonrails** [comment]
Thanks @RanadeepPolavarapu! I'll be taking a look this week.
